In [0]:
import requests
import lxml.html as lh
import pandas as pd

In [0]:
url='https://www.worldometers.info/coronavirus/'
#Create a handle, page, to handle the contents of the website
page = requests.get(url)
#Store the contents of the website under doc
doc = lh.fromstring(page.content)
#Parse data that are stored between <tr>..</tr> of HTML
tr_elements = doc.xpath('//tr')

In [58]:
tr_elements = doc.xpath('//tr')
#Create empty list
col=[]
i=0
#For each row, store each first element (header) and an empty list
for tr_element in tr_elements[0]:
    i+=1
    name=tr_element.text_content()
    print ('%d:"%s"'%(i,name))
    col.append((name,[]))

1:"Country,Other"
2:"TotalCases"
3:"NewCases"
4:"TotalDeaths"
5:"NewDeaths"
6:"TotalRecovered"
7:"ActiveCases"
8:"Serious,Critical"
9:"Tot Cases/1M pop"
10:"Deaths/1M pop"
11:"TotalTests"
12:"Tests/
1M pop
"
13:"Continent"

In [0]:
#Since out first row is the header, data is stored on the second row onwards
for j in range(1,len(tr_elements)):
    #T is our j'th row
    T=tr_elements[j]
    
    
    #i is the index of our column
    i=0
    
    #Iterate through each element of the row
    for t in T.iterchildren():
        data=t.text_content() 
        #Append the data to the empty list of the i'th column
        col[i][1].append(data)
        #Increment i for the next column
        i+=1

In [0]:
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [0]:
pd.set_option('display.max_rows', df.shape[0]+1)

In [62]:
df

              Country,Other  TotalCases  ...  Tests/\n1M pop\n          Continent
0         \nNorth America\n     569,587  ...                        North America
1                \nEurope\n     861,284  ...                               Europe
2                  \nAsia\n     288,849  ...                                 Asia
3         \nSouth America\n      48,103  ...                        South America
4               \nOceania\n       7,730  ...                    Australia/Oceania
5                \nAfrica\n      14,299  ...                               Africa
6                      \n\n         721  ...
7                     World   1,790,573  ...                                  All
8                       USA     533,115  ...             8,138      North America
9                     Spain     166,019  ...             7,593             Europe
10                    Italy     152,271  ...            15,935             Europe
11                   France     129,654  ...             5,114             Europe
12                  Germany     125,452  ...            15,730             Europe
13                       UK      78,991  ...             4,934             Europe
14                     Iran      70,029  ...             2,997               Asia
15                   Turkey      52,167  ...             4,036               Asia
16                  Belgium      29,647  ...             8,814             Europe
17              Switzerland      25,300  ...            21,954             Europe
18              Netherlands      24,413  ...             5,926             Europe
19                   Canada      23,318  ...            10,639      North America
20                   Brazil      20,964  ...               296      South America
21                 Portugal      15,987  ...            15,966             Europe
22                   Russia      15,770  ...             8,223             Europe
23                  Austria      13,945  ...            16,086             Europe
24                   Israel      10,878  ...            13,557               Asia
25                 S. Korea      10,512  ...            10,038               Asia
26                   Sweden      10,151  ...             5,416             Europe
27                  Ireland       8,928  ...            10,734             Europe
28                    India       8,504  ...               137               Asia
29                  Ecuador       7,257  ...             1,222      South America
30                    Chile       6,927  ...             3,995      South America
31                     Peru       6,848  ...             2,054      South America
32                    Japan       6,748  ...               544               Asia
33                   Norway       6,409  ...            22,924             Europe
34                   Poland       6,356  ...             3,423             Europe
35                Australia       6,313  ...            13,880  Australia/Oceania
36                  Romania       6,300  ...             3,240             Europe
37                  Denmark       5,996  ...            11,700             Europe
38                  Czechia       5,905  ...            11,684             Europe
39                 Pakistan       5,038  ...               280               Asia
40                 Malaysia       4,683  ...             2,221               Asia
41              Philippines       4,648  ...               309               Asia
42                Indonesia       4,241  ...                71               Asia
43                   Mexico       4,219  ...               275      North America
44             Saudi Arabia       4,033  ...             3,320               Asia
45                      UAE       3,736  ...            65,538               Asia
46                   Serbia       3,380  ...             1,877             Europe
47               Luxembourg       3,270  ...            46,272             Europe
48                   Panama       3,234  ...             3,381      North America
49                  Finland       2,974  ...             8,125             Europe
50                  Ukraine       2,777  ...               693             Europe
51       Dominican Republic       2,759  ...               781      North America
52                    Qatar       2,728  ...            16,574               Asia
53                 Colombia       2,709  ...               798      South America
54                  Belarus       2,578  ...             6,773             Europe
55                 Thailand       2,551  ...             1,030               Asia
56                Singapore       2,299  ...            12,423               Asia
57                Argentina       2,142  ...               399      South America
58                   Greece       2,081  ...             3,583             Europe
59             South Africa       2,028  ...             1,265             Africa
60                    Egypt       1,939  ...               244             Africa
61                  Algeria       1,825  ...                77             Africa
62                  Iceland       1,689  ...           101,497             Europe
63                  Morocco       1,617  ...               230             Africa
64                  Moldova       1,560  ...             1,555             Europe
65                  Croatia       1,534  ...             3,822             Europe
66                  Hungary       1,410  ...             3,471             Europe
67              New Zealand       1,330  ...            12,684  Australia/Oceania
68                     Iraq       1,318  ...               843               Asia
69                  Estonia       1,309  ...            22,878             Europe
70                   Kuwait       1,234  ...                                 Asia
71                 Slovenia       1,205  ...            16,764             Europe
72               Azerbaijan       1,058  ...             6,050               Asia
73                Lithuania       1,053  ...            14,132             Europe
74                  Bahrain       1,040  ...            35,511               Asia
75                  Armenia       1,013  ...             2,418               Asia
76                Hong Kong       1,005  ...            12,900               Asia
77   Bosnia and Herzegovina         975  ...             3,103             Europe
78               Kazakhstan         897  ...             3,691               Asia
79                 Cameroon         820  ...                               Africa
80               Uzbekistan         796  ...             2,091               Asia
81          North Macedonia         760  ...             3,673             Europe
82                 Slovakia         742  ...             5,023             Europe
83         Diamond Princess         712  ...
84                  Tunisia         685  ...               903             Africa
85                 Bulgaria         669  ...             2,663             Europe
86                   Latvia         651  ...            14,958             Europe
87                  Lebanon         630  ...             2,220               Asia
88               Bangladesh         621  ...                59               Asia
89                     Cuba         620  ...             1,162      North America
90                   Cyprus         616  ...            14,179               Asia
91              Afghanistan         607  ...                                 Asia
92                  Andorra         601  ...            21,653             Europe
93                     Oman         599  ...                                 Asia
94               Costa Rica         577  ...             1,297      North America
95              Ivory Coast         533  ...                               Africa
96                  Uruguay         501  ...             2,336      South America
97                    Niger         491  ...               178             Africa
98             Burkina Faso         484  ...                               Africa
99                  Albania         446  ...             1,347             Europe
100                   Ghana         408  ...             1,204             Africa
101         Channel Islands         407  ...            19,095             Europe
102                Honduras         393  ...               162      North America
103                  Taiwan         388  ...             1,954               Asia
104                 Réunion         388  ...                               Africa
105                  Jordan         381  ...             2,009               Asia
106                   Malta         378  ...            36,273             Europe
107              Kyrgyzstan         377  ...             1,474               Asia
108              San Marino         356  ...            24,933             Europe
109               Mauritius         319  ...             5,565             Africa
110                 Nigeria         318  ...                24             Africa
111                 Bolivia         300  ...               187      South America
112                 Senegal         278  ...                               Africa
113               Palestine         268  ...             3,331               Asia
114              Montenegro         267  ...             4,568             Europe
115                 Vietnam         258  ...             1,252               Asia
116                 Georgia         252  ...               820               Asia
117                  Guinea         250  ...                               Africa
118             Isle of Man         226  ...            22,744             Europe
119                     DRC         223  ...                               Africa
120               Sri Lanka         203  ...               211               Asia
121                 Mayotte         196  ...             4,948             Africa
122                   Kenya         191  ...               115             Africa
123                Djibouti         187  ...             4,066             Africa
124          Faeroe Islands         184  ...           112,744             Europe
125               Venezuela         175  ...             6,377      South America
126              Martinique         155  ...                        North America
127               Guatemala         153  ...                63      North America
128              Guadeloupe         143  ...                        North America
129                 Brunei          136  ...            22,593               Asia
130                Paraguay         134  ...               317      South America
131               Gibraltar         129  ...            46,244             Europe
132             El Salvador         125  ...                        North America
133                Cambodia         122  ...               345               Asia
134                  Rwanda         120  ...                62             Africa
135     Trinidad and Tobago         112  ...               787      North America
136              Madagascar         102  ...                               Africa
137                  Monaco          92  ...                               Europe
138                   Aruba          92  ...            10,471      North America
139                    Mali          87  ...                               Africa
140           French Guiana          86  ...                        South America
141           Liechtenstein          79  ...            23,605             Europe
142                    Togo          76  ...               250             Africa
143                Ethiopia          71  ...                34             Africa
144                 Jamaica          69  ...               306      North America
145                Barbados          68  ...             2,599      North America
146                   Congo          60  ...                               Africa
147          Cayman Islands          53  ...             8,156      North America
148                  Uganda          53  ...               106             Africa
149        French Polynesia          51  ...             2,649  Australia/Oceania
150            Sint Maarten          50  ...             3,125      North America
151                 Bermuda          50  ...             6,680      North America
152                   Gabon          49  ...                               Africa
153                 Liberia          48  ...                               Africa
154                 Bahamas          46  ...                        North America
155                  Guyana          45  ...               245      South America
156                   Macao          45  ...                                 Asia
157                  Zambia          40  ...                67             Africa
158                 Myanmar          38  ...                26               Asia
159           Guinea-Bissau          38  ...               762             Africa
160                   Benin          35  ...                               Africa
161                 Eritrea          34  ...                               Africa
162                   Haiti          33  ...                32      North America
163                Tanzania          32  ...                               Africa
164            Saint Martin          32  ...                        North America
165                   Syria          25  ...                                 Asia
166                   Libya          25  ...                74             Africa
167     Antigua and Barbuda          21  ...               408      North America
168                 Somalia          21  ...                               Africa
169                Maldives          20  ...                                 Asia
170              Mozambique          20  ...                18             Africa
171                  Angola          19  ...                               Africa
172                   Sudan          19  ...                               Africa
173                    Laos          19  ...               157               Asia
174       Equatorial Guinea          18  ...               609             Africa
175           New Caledonia          18  ...             9,135  Australia/Oceania
176                Dominica          16  ...             4,293      North America
177                    Fiji          16  ...                    Australia/Oceania
178                Mongolia          16  ...                                 Asia
179                 Namibia          16  ...               142             Africa
180             Saint Lucia          15  ...                        North America
181                Zimbabwe          14  ...                37             Africa
182                 Curaçao          14  ...                        North America
183                 Grenada          14  ...               818      North America
184                Eswatini          14  ...                               Africa
185                  Belize          13  ...               915      North America
186                Botswana          13  ...             1,075             Africa
187                  Malawi          12  ...                12             Africa
188                   Nepal          12  ...               152               Asia
189   Saint Kitts and Nevis          12  ...             3,853      North America
190  St. Vincent Grenadines          12  ...               505      North America
191                    Chad          11  ...                               Africa
192               Greenland          11  ...            13,564      North America
193              Seychelles          11  ...                               Africa
194                Suriname          10  ...                        South America
195            Sierra Leone          10  ...                               Africa
196              MS Zaandam           9  ...
197                  Gambia           9  ...               116             Africa
198               Nicaragua           9  ...                        North America
199        Turks and Caicos           9  ...             1,601      North America
200              Montserrat           9  ...             7,212      North America
201              Cabo Verde           8  ...                               Africa
202                     CAR           8  ...                               Africa
203            Vatican City           8  ...                               Europe
204              Mauritania           7  ...                82             Africa
205               St. Barth           6  ...                        North America
206          Western Sahara           6  ...                               Africa
207                  Bhutan           5  ...             1,511               Asia
208                 Burundi           5  ...                               Africa
209        Falkland Islands           5  ...            39,368      South America
210   Sao Tome and Principe           4  ...                87             Africa
211             South Sudan           4  ...                               Africa
212                Anguilla           3  ...                        North America
213  British Virgin Islands           3  ...                        North America
214   Caribbean Netherlands           3  ...               381      North America
215        Papua New Guinea           2  ...                 8  Australia/Oceania
216             Timor-Leste           2  ...                                 Asia
217   Saint Pierre Miquelon           1  ...                        North America
218                   Yemen           1  ...                                 Asia
219                   China      82,052  ...                                 Asia
220                  Total:     569,587  ...                        North America
221                  Total:     861,284  ...                               Europe
222                  Total:     288,849  ...                                 Asia
223                  Total:      48,103  ...                        South America
224                  Total:       7,730  ...                    Australia/Oceania
225                  Total:      14,299  ...                               Africa
226                  Total:         721  ...
227                  Total:   1,790,573  ...                                  All
228           Country,Other  TotalCases  ...  Tests/\n1M pop\n          Continent
229                \nAsia\n     287,184  ...                                 Asia
230       \nNorth America\n     568,949  ...                        North America
231              \nEurope\n     852,899  ...                               Europe
232       \nSouth America\n      48,068  ...                        South America
233             \nOceania\n       7,702  ...                    Australia/Oceania
234              \nAfrica\n      14,220  ...                               Africa
235                    \n\n         721  ...
236                   World   1,779,743  ...                                  All
237                   China      81,953  ...                                 Asia
238                     USA     532,879  ...             8,068      North America
239                   Spain     163,027  ...             7,593             Europe
240                   Italy     152,271  ...            15,935             Europe
241                  France     129,654  ...             5,114             Europe
242                 Germany     125,452  ...            15,730             Europe
243                      UK      78,991  ...             4,934             Europe
244                    Iran      70,029  ...             2,997               Asia

In [63]:
df.shape

(457, 13)

In [0]:
df.set_index("Country,Other", inplace= True)

In [65]:
df.loc['Nepal']

              TotalCases NewCases  ... Tests/\n1M pop\n Continent
Country,Other                      ...
Nepal                 12       +3  ...              152      Asia
Nepal                  9           ...              152      Asia

[2 rows x 12 columns]

In [66]:
df.head()

                  TotalCases NewCases  ... Tests/\n1M pop\n          Continent
Country,Other                          ...
\nNorth America\n    569,587     +638  ...                       North America
\nEurope\n           861,284   +8,385  ...                              Europe
\nAsia\n             288,849   +1,665  ...                                Asia
\nSouth America\n     48,103      +35  ...                       South America
\nOceania\n            7,730      +28  ...                   Australia/Oceania

[5 rows x 12 columns]